export class CandidateModel {
    candidateID : string | undefined;
    PostID?: string;
    Source?:string;
    logUserName?:string;
    SkillName?:string;
    Surname?:string;
    CandidateFirstName?:string;
    FatherName?:string;
    HusbandName?:string;
    DOB?:Date;
    Gender?:boolean;
    MaritalStatus?:number;
    Address?:string;
    City?:string;
    State?:string;
    PIN?:number;
    Mobile?:string;
    CandidateEmail?:string;
    Tno?:string;
    LanguagesKnown?:string;
    CurrentCTC?:number;
    ExpectedCTC?:number;
    NoticePeriod?:number;
    TotalExperience?:number;
    HoldAnyOffer?:boolean;
    UserId?:string;
    Course1?:string;
    School1?:string;
    Yearofpassing1?:number |undefined;
    PercentageofMarks1?:number;
    DistinctionORAwardsReceived1?:string;
    Course2?:string;
    School2?:string;
    Yearofpassing2?:number;
    PercentageofMarks2?:number;
    DistinctionORAwardsReceived2?:string;
    Course3?:string;
    School3?:string;
    Yearofpassing3?:number;
    PercentageofMarks3?:number;
    DistinctionORAwardsReceived3?:string;
    Course4?:string;
    School4?:string;
    Yearofpassing4?:number;
    PercentageofMarks4?:number;
    DistinctionORAwardsReceived4?:string;
    Organization1?:string;
    PositionHeld1?:string;
    StartingSalary1?:string;
    LastDrawnSalary1?:number;
    DOJ1?:Date | null;
    DOL1?:Date| null;
    ROL1?:string;
    Organization2?:string;
    PositionHeld2?:string;
    StartingSalary2?:number;
    LastDrawnSalary2?:number;
    DOJ2?:Date | null;
    DOL2?:Date | null;
    ROL2?:string;
    Organization3?:string;
    PositionHeld3?:string;
    StartingSalary3?:number;
    LastDrawnSalary3?:number;
    DOJ3?:Date | null;
    DOL3?:Date | null;
    ROL3?:string;
    Organization4?:string;
    PositionHeld4?:string;
    StartingSalary4?:number;
    LastDrawnSalary4?:number;
    DOJ4?:Date | null;
    DOL4?:Date | null;
    ROL4?:string;
    InterviewDate1?:Date;
    Interviewer1?:string;
    ModeofInterview1?:number;
    RatingTechinical1?:number;
    RatingCommunication1?:number;
    RatingTest1?:number;
    Comments1?:string;
    InterviewStatus1?:number;
    InterviewDate2?:Date;
    Interviewer2?:string;
    ModeofInterview2?:number;
    RatingTechinical2?:number;
    RatingCommunication2?:number;
    RatingTest2?:number;
    Comments2?:string;
    InterviewStatus2?:number;
    InterviewDate3?:Date;
    Interviewer3?:string;
    ModeofInterview3?:number;
    RatingTechinical3?:number;
    RatingCommunication3?:number;
    RatingTest3?:number;
    Comments3?:string;
    InterviewStatus3?:number;
    HRFeedback?:string;
    FinalStatus?:number;
    CandidateType?:number;
    JobTitle?:string;
    JobType?:number;
    VendorNameOREmployerName?:string;
    PassportNo?:string;
    Nationality?:string;
    VisaType?:number;
    IndiaResidenceAddress?:string;
    ForeignResidenceAddress?:string;
    DriverLicence?:string;
    SSN?:string;
    CandidateTypeData?:string;
    FilePath?: string;
    }
    